// This script changes rendering mode, generated by AI

const container = document.getElementById('canvas');
const selector = document.getElementById('script-selector');

let currentModule = null;

function clearPreviousScene() {
  if (currentModule && currentModule.stop) {
    currentModule.stop();
  }
}

async function loadModule(modulePath) {
  clearPreviousScene();

  const module = await import(`./${modulePath}`);
    currentModule = module;
    currentModule.init(container);
    console.log(`Loaded module: ${modulePath}`);
}

selector.addEventListener('change', (event) => {
  const selectedModule = event.target.value;
  loadModule(selectedModule);
});


loadModule(selector.value);
